### ISSUE TITLE
Unable to clone ignitionrobotics/ign-cmake repository

### ISSUE THREAD

**Issue by GiulioRomualdi** [traversaro/gazebo-superbuild#7]
When I run `make` on ubuntu I get the following error
```
[  1%] Performing download step (hg clone) for 'ignition-cmake0'
abort: HTTP Error 404: Not Found
CMake Error at /home/gromualdi/robot-code/gazebo-superbuild/build/osrf/ignition-cmake0/CMakeFiles/YCMTmp/ignition-cmake0-hgclone.cmake:30 (message):
  Failed to clone repository:
  'https://bitbucket.org/ignitionrobotics/ign-cmake'


CMakeFiles/ignition-cmake0.dir/build.make:109: recipe for target 'osrf/ignition-cmake0/CMakeFiles/YCMStamp/ignition-cmake0-download' failed
make[2]: *** [osrf/ignition-cmake0/CMakeFiles/YCMStamp/ignition-cmake0-download] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/ignition-cmake0.dir/all' failed
make[1]: *** [CMakeFiles/ignition-cmake0.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by traversaro** [comment]
I hoped you were not serious when you told me you were using this repo! : ) 

Jokes apart, Ignition repos have been migrated to GitHub now (https://community.gazebosim.org/t/important-gazebo-and-ignition-are-going-to-github/533), so to get this repo to work it is not necessary to change all the BitBucket/Mercurial URL  to GitHub/Git . If you are interested in this, feel free to open a PR. However, to be honest I kind of halted working on this repo as the procedure to build  the Gazebo repos with colcon is relatively straightforward, and I started using that. The basic docs are available in https://colcon.readthedocs.io/en/released/user/quick-start.html#build-gazebo-and-the-ignition-packages , and the up-to-date `.yaml` file with the correct branches for each Gazebo version are available in https://github.com/ignition-tooling/gazebodistro .

**Comment by GiulioRomualdi** [comment]
Thanks for the suggestion @traversaro. @xenvre may be interested in https://github.com/traversaro/gazebo-superbuild/issues/7#issuecomment-651697615 as well.

**Comment by traversaro** [comment]
The colcon strategy is also the way with which we build the Gazebo binaries for Windows in https://github.com/robotology/robotology-superbuild-dependencies-vcpkg/blob/master/.github/workflows/ci.yml#L158 .

**Comment by traversaro** [comment]
@GiulioRomualdi @xEnVrE if the colcon workflow is working well for you, I would go ahead and deprecated this repo, removing its  content and just placing in the README the instructions on how to build Gazebo with colcon.

**Comment by GiulioRomualdi** [comment]
Hi @traversaro I was able to clone and build the repo with `colcon`. From my side, you can deprecate this repo.

**Comment by xEnVrE** [comment]
I did not have time to test it. Given Giulio's tests, it is fine for me too.

**Comment by traversaro** [comment]
Ok, I guess colcon is enough for anyone.
